name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest​
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint
        
      - name: Test app 
        run: yarn test
